### PR TITLE
FEAT: Initial commit

### PR DESCRIPTION
**Pull request by arulk8**
Desc:
Added products list UI changes, added global store, added Routing setup,
Added Header(still in progress)

### CODE REVIEW

**Review by sashaboi — APPROVED** [review]
The setup looks good ! 
Hoping to see a hosted version for easy reviews later as well, hope you get to that.

**Comment by sohan9819** [comment]
Setup looks good please host the project , it will me much more better to review

**Review by sohan9819 — APPROVED** [review]
Setup looks good please host the project , it will me much more better to review

**Comment by arulk8** [comment]
> The setup looks good ! Hoping to see a hosted version for easy reviews later as well, hope you get to that.

Yeah i will host from next time onwards

**Comment by arulk8** [comment]
> Setup looks good please host the project , it will me much more better to review

Yeah I will host from next time onwards

**Pull request merged**
